# ExplorAstur Configuration

# Event sources
sources:
  # Blog Telecable Asturias
  - name: Blog Telecable Asturias
    url: https://blog.telecable.es/agenda-planes-asturias/
    category: Oficial
    # This source uses a specialized parser in the code
    # No additional selectors needed as it parses directly from the HTML structure

# Note: Additional sources can be added here